version: "3.9"
services:

  classifier:
    build: ./classifier
    env_file: .env
    expose:
      - "${CLASSIFIER_PORT}"
    depends_on:
      - database

  database:
    build: ./database
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/


volumes:
  postgres_data:
