version: "3.9"
services:

  classifier:
    build: ./classifier
    env_file: .env
    expose:
      - "${CLASSIFIER_PORT}"
    depends_on:
      - database
    volumes:
      - type: bind
        source: ./static
        target: /static

  database:
    build: ./database
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  
  ground_truth_updater:
    build: ./ground_truth_updater
    env_file: .env
    depends_on: 
      - database
    environment:
      - STREAMLIT_SERVER_PORT=8081
    ports:
      - "8081:8081"
    
  
  dashboard:
    build: ./dashboard
    env_file: .env
    depends_on:
      - database
    environment:
      - STREAMLIT_SERVER_PORT=8080
    ports:
      - "8080:8080"
  
  fake_twitter:
    build: ./fake_twitter
    env_file: .env
    volumes:
      - type: bind
        source: ./static
        target: /static

  client:
    build: ./client
    env_file: .env
    depends_on:
      - fake_twitter
      - classifier
    environment:
      - STREAMLIT_SERVER_PORT=80
    ports:
      - "80:80"


volumes:
  postgres_data:
