version: "3.9"
services:

  classifier:
    build: ./classifier
    env_file: .env
    expose:
      - "${CLASSIFIER_PORT}"
    depends_on:
      - database

  database:
    # image: postgres
    build: ./database
    env_file: .env
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data/
    # environment:
    #   - POSTGRES_USER=root
    #   - POSTGRES_PASSWORD=root
    #   - POSTGRES_DB=root


# volumes:
#   postgres_data:
